name: Deploy


on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # 运行在 ubuntu 系统环境下
    steps:
      - uses: actions/checkout@v2 # uses 命令允许我们使用别人定义好的 Action，这里是从仓库检出分支
      - uses: actions/setup-node@v2 # 这里是设置 node 版本
        with:
          node-version: 16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.6.0
      - name: Install Dependencies # name 定义步骤的名称，这个可以在该 Action 运行起来之后，在 Github Actions Tab 下看到
        run: | # `run: |` 的方式，允许我们一次定义多个要执行的命令
          pnpm install
          pnpm build
      - name: Push To Pages
        working-directory: ./.vitepress/dist # 指定下面指令运行的目录
        run: |
          git init
          git checkout -b main
          git add -A
        # 这里把下面所有 `<YOUR_NAME>/<YOUR_EMAIL>/<COMMIT_MSG>/<YOUR_TOKEN>` 替换成你自己的就可以了
          git -c user.name='TwoBeefly' -c user.email='<YOUR_EMAIL>' commit -m '<COMMIT_MSG>'
        # 这里需要一个 共开仓库 的 secrets 配置，这里的 secrets 是一个环境变量，可以直接拿过来直接用
          git remote add origin https://${{secrets.<YOUR_TOKEN>}}@github.com/<YOUR_NAME>/blog.git
          git push origin main -f -q